{% set version = "1.1.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-finalfit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/finalfit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/finalfit/finalfit_{{ version }}.tar.gz
  sha256: 480bf93724b66a1565699c4c6411a2b509ef740984f8ba8320621784181dd3a2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic

requirements:
  build:
    - {{ posix }}zip  # [win]

  host:
    - r-base
    - r-bdsmatrix
    - r-boot
    - r-broom
    - r-cowplot
    - r-dplyr
    - r-forcats
    - r-ggally
    - r-ggplot2
    - r-gridextra
    - r-lme4
    - r-magrittr
    - r-mice >=3.17.0
    - r-pillar
    - r-proc
    - r-purrr
    - r-scales
    - r-stringr
    - r-survival
    - r-tidyr >=1.0.0

  run:
    - r-base
    - r-bdsmatrix
    - r-boot
    - r-broom
    - r-cowplot
    - r-dplyr
    - r-forcats
    - r-ggally
    - r-ggplot2
    - r-gridextra
    - r-lme4
    - r-magrittr
    - r-mice >=3.17.0
    - r-pillar
    - r-proc
    - r-purrr
    - r-scales
    - r-stringr
    - r-survival
    - r-tidyr >=1.0.0

test:
  commands:
    - $R -e "library('finalfit')"  # [not win]
    - "\"%R%\" -e \"library('finalfit')\""  # [win]

about:
  home: https://github.com/ewenharrison/finalfit
  license: MIT
  summary: Generate regression results tables and plots in final format for publication. Explore models and export directly to PDF and 'Word' using 'RMarkdown'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENCE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: finalfit
# Type: Package
# Title: Quickly Create Elegant Regression Results Tables and Plots when Modelling
# Version: 1.0.5
# Authors@R: c( person(given = "Ewen", family = "Harrison", role = c("aut", "cre"), email = "ewen.harrison@ed.ac.uk"), person(given = "Tom", family = "Drake", role = c("aut")), person(given = "Riinu", family = "Ots", role = c("aut")))
# Maintainer: Ewen Harrison <ewen.harrison@ed.ac.uk>
# Description: Generate regression results tables and plots in final format for publication. Explore models and export directly to PDF and 'Word' using 'RMarkdown'.
# License: MIT + file LICENCE
# Encoding: UTF-8
# LazyData: true
# BugReports: https://github.com/ewenharrison/finalfit/issues
# URL: https://github.com/ewenharrison/finalfit
# Imports: bdsmatrix, boot, broom, dplyr, forcats, GGally, ggplot2, grid, gridExtra, lme4, magrittr, mice, pillar, pROC, purrr, scales, stats, stringr, survival, tidyr (>= 1.0.0), tidyselect
# RoxygenNote: 7.2.1
# Suggests: cmprsk, coxme, knitr, lmtest, readr, rlang, rmarkdown, rstan, sandwich, survey, survminer, testthat, tibble
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-08-09 17:27:45 UTC; eharrison
# Author: Ewen Harrison [aut, cre], Tom Drake [aut], Riinu Ots [aut]
# Repository: CRAN
# Date/Publication: 2022-08-09 18:30:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
